CREATE DATABASE BTL_CNW
GO
USE BTL_CNW
GO

CREATE TABLE KhachHang
(
	makh INT IDENTITY(1,1) NOT NULL,
	hotenkh NVARCHAR(50),
	diachi NVARCHAR(500),
	sdt NCHAR(15),
	email NCHAR(50),
	taikhoan NCHAR(100),
	matkhau NCHAR(50)
)

CREATE TABLE LoaiTraSua
(
	maloai INT IDENTITY(1,1) NOT NULL,
	tenloai NVARCHAR(100)
)

CREATE TABLE TraSua
(
	mats INT IDENTITY(1,1),
	maloai INT,
	tents NVARCHAR(100),
	huongvi NVARCHAR(50),
	size NCHAR(5),
	dongia DECIMAL(15,2),
	anhts NVARCHAR(100),
	ghichu NVARCHAR(500)
)

CREATE TABLE NhanVien
(
	manv INT IDENTITY(1,1) NOT NULL,
	tennv NVARCHAR(50),
	taikhoannv NCHAR(50),
	matkhaunv NCHAR(50)
)

CREATE TABLE DatHang
(
	madh INT IDENTITY NOT NULL,
	makh INT,
	tongtien DECIMAL(15,2),
	ngaytao DATE,
	Note NVARCHAR(100)
)

CREATE TABLE CTDatHang
(
	mactdh INT IDENTITY NOT NULL,
	madh INT NOT NULL,
	mats INT,
	soluong INT,
	dongia DECIMAL(15,2),
	thanhtien DECIMAL(15,2)
)

GO

ALTER TABLE dbo.NhanVien ADD CONSTRAINT PK_NHANVIEN_MaNV PRIMARY KEY (manv)
ALTER TABLE dbo.KhachHang ADD CONSTRAINT PK_KHACHHANG_MaKH PRIMARY KEY (makh)
ALTER TABLE dbo.TraSua ADD CONSTRAINT PK_TRASUA_MaTS PRIMARY KEY (mats)
ALTER TABLE dbo.LoaiTraSua ADD CONSTRAINT PK_LOAITS_MaLoai PRIMARY KEY (maloai)
ALTER TABLE dbo.DatHang ADD CONSTRAINT PK_DONHANG_MaDH PRIMARY KEY (madh)
ALTER TABLE dbo.CTDatHang ADD CONSTRAINT PK_CTDONHANG_MaCTDH PRIMARY KEY (mactdh)
ALTER TABLE dbo.DatHang ADD CONSTRAINT FK_KHACHHANG_MaKH FOREIGN KEY (makh) REFERENCES dbo.KhachHang(makh)
ALTER TABLE dbo.CTDatHang ADD CONSTRAINT FK_DONHANG_MaDH FOREIGN KEY (madh) REFERENCES dbo.DatHang(madh) 
ALTER TABLE dbo.CTDatHang ADD CONSTRAINT FK_TRASUA_MaTS FOREIGN KEY (mats) REFERENCES dbo.TraSua(mats)
ALTER TABLE dbo.TraSua ADD CONSTRAINT FK_LOAITS_MaLoai FOREIGN KEY (maloai) REFERENCES dbo.LoaiTraSua(maloai)
GO

CREATE PROC SEARCHSP
	@TENTS NVARCHAR(100)
AS
	BEGIN SELECT * FROM dbo.TraSua
	WHERE tents LIKE N'%' + @TENTS + '%'
	END
GO

CREATE PROC SEARCHSP_ADMIN
	@TENTS NVARCHAR(100),
	@TENLOAI NVARCHAR(100),
	@TUGIA DECIMAL,
	@DENGIA DECIMAL
AS
	BEGIN SELECT * FROM dbo.TraSua, dbo.LoaiTraSua
	WHERE dbo.TraSua.maloai = dbo.LoaiTraSua.maloai AND
		tents LIKE N'%' + @TENTS + '%' AND
		dbo.LoaiTraSua.tenloai LIKE N'%' + @TENLOAI + N'%' AND
		dongia > @TUGIA AND dongia < @DENGIA 	
	END
GO


 
